In [1]:
#Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("/content/sampledata.csv")

Data Description

In [3]:
dataset.describe()

,Unnamed: 0,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,...,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
count,7240.000000,7240.000000,3173.000000,3209.000000,3206.000000,3219.000000,3223.000000,3218.000000,3209.000000,3174.000000,...,184.000000,185.000000,182.000000,190.000000,184.000000,182.000000,183.000000,183.000000,183.000000,185.000000
mean,3620.500000,1996.556768,83.710054,1015.660019,1403.800998,1315.884747,1103.857276,800.698881,682.818947,114.328607,...,1835.070652,1525.302703,1426.000000,532.836842,1161.853261,1472.802198,1125.010929,877.267760,686.409836,683.762162
std,2090.152307,9.828904,316.136459,4885.378588,5718.387178,6003.260603,5441.061415,4418.309010,4089.137785,504.633674,...,8324.282351,8760.267951,9431.992775,2117.777714,4606.763119,5259.592231,4210.577991,3556.178992,3379.328224,3618.471096
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1810.750000,1988.000000,0.000000,9.000000,14.000000,13.000000,12.000000,8.000000,8.000000,1.000000,...,19.000000,13.000000,17.000000,5.000000,10.750000,18.000000,12.500000,10.000000,8.000000,9.000000
50%,3620.500000,1997.000000,5.000000,90.000000,150.000000,130.000000,102.000000,63.000000,53.000000,7.000000,...,175.000000,136.000000,117.000000,32.500000,123.000000,161.000000,125.000000,92.000000,69.000000,69.000000
75%,5430.250000,2005.000000,37.000000,502.000000,715.500000,583.500000,440.000000,279.000000,232.000000,50.750000,...,688.500000,536.000000,453.500000,226.000000,587.750000,762.500000,544.500000,400.500000,269.000000,339.000000
max,7240.000000,2013.000000,5001.000000,78278.000000,84003.000000,90830.000000,82921.000000,63814.000000,70376.000000,8576.000000,...,100297.000000,112558.000000,124476.000000,18054.000000,49491.000000,44985.000000,38804.000000,37138.000000,40892.000000,47438.000000

In [4]:
dataset.head()

,Unnamed: 0,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,1,Afghanistan,AF,AFG,1980,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Afghanistan,AF,AFG,1981,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Afghanistan,AF,AFG,1982,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Afghanistan,AF,AFG,1983,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Afghanistan,AF,AFG,1984,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dataset.dtypes

Unnamed: 0        int64
country          object
iso2             object
iso3             object
year              int64
                 ...
newrel_f2534    float64
newrel_f3544    float64
newrel_f4554    float64
newrel_f5564    float64
newrel_f65      float64
Length: 61, dtype: object

In [6]:
dataset["iso2"].head(5)

0    AF
1    AF
2    AF
3    AF
4    AF
Name: iso2, dtype: object

In [7]:
dataset["iso3"].head(5)

0    AFG
1    AFG
2    AFG
3    AFG
4    AFG
Name: iso3, dtype: object

Columns like **Country,iso2,iso3** these all seems to represent a country so iso2,iso3 are eliminated. Only country column is taken.

In [8]:
#No missing values in the country column
nan_count = dataset["country"].isnull().isnull().sum().sum()
print(nan_count)

0

In [9]:
dataset = dataset.drop(['iso2'], axis=1)

In [10]:
dataset = dataset.drop(['iso3'], axis=1)

In [11]:
dataset.head(5)

,Unnamed: 0,country,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,...,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,1,Afghanistan,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Afghanistan,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Afghanistan,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Afghanistan,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Afghanistan,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

View all column names

In [12]:
column_headers = list(dataset.columns.values)
print("The Column Header :", column_headers)

The Column Header : ['Unnamed: 0', 'country', 'year', 'new_sp_m014', 'new_sp_m1524', 'new_sp_m2534', 'new_sp_m3544', 'new_sp_m4554', 'new_sp_m5564', 'new_sp_m65', 'new_sp_f014', 'new_sp_f1524', 'new_sp_f2534', 'new_sp_f3544', 'new_sp_f4554', 'new_sp_f5564', 'new_sp_f65', 'new_sn_m014', 'new_sn_m1524', 'new_sn_m2534', 'new_sn_m3544', 'new_sn_m4554', 'new_sn_m5564', 'new_sn_m65', 'new_sn_f014', 'new_sn_f1524', 'new_sn_f2534', 'new_sn_f3544', 'new_sn_f4554', 'new_sn_f5564', 'new_sn_f65', 'new_ep_m014', 'new_ep_m1524', 'new_ep_m2534', 'new_ep_m3544', 'new_ep_m4554', 'new_ep_m5564', 'new_ep_m65', 'new_ep_f014', 'new_ep_f1524', 'new_ep_f2534', 'new_ep_f3544', 'new_ep_f4554', 'new_ep_f5564', 'new_ep_f65', 'newrel_m014', 'newrel_m1524', 'newrel_m2534', 'newrel_m3544', 'newrel_m4554', 'newrel_m5564', 'newrel_m65', 'newrel_f014', 'newrel_f1524', 'newrel_f2534', 'newrel_f3544', 'newrel_f4554', 'newrel_f5564', 'newrel_f65']

In [13]:
dataset_df = pd.DataFrame(dataset) #to dataframe

In [14]:
# Melt the DataFrame
value_vars = dataset_df.columns.difference(['Unnamed: 0', 'year']).tolist()

df_long = pd.melt(dataset_df, id_vars=['Unnamed: 0','country','year'],value_vars=value_vars,
 var_name='key', value_name='cases')

# Drop rows with NA values in the 'cases' column
df_long = df_long.dropna(subset=['cases'])

In [15]:
df_long.head(5)

    Unnamed: 0  country  year          key  cases
60          61  Albania  2006  new_ep_f014    7.0
61          62  Albania  2007  new_ep_f014    1.0
62          63  Albania  2008  new_ep_f014    3.0
63          64  Albania  2009  new_ep_f014    2.0
64          65  Albania  2010  new_ep_f014    2.0

In [16]:
df_long.describe

<bound method NDFrame.describe of         Unnamed: 0                             country  year          key  \
60              61                             Albania  2006  new_ep_f014
61              62                             Albania  2007  new_ep_f014
62              63                             Albania  2008  new_ep_f014
63              64                             Albania  2009  new_ep_f014
64              65                             Albania  2010  new_ep_f014
...            ...                                 ...   ...          ...
405235        7036  Venezuela (Bolivarian Republic of)  2013   newrel_m65
405269        7070                            Viet Nam  2013   newrel_m65
405371        7172                               Yemen  2013   newrel_m65
405405        7206                              Zambia  2013   newrel_m65
405439        7240                            Zimbabwe  2013   newrel_m65

         cases
60         7.0
61         1.0
62         3.0
63         2.0
64         2.0
...        ...
405235   523.0
405269  5834.0
405371   446.0
405405  1112.0
405439  1208.0

[76046 rows x 5 columns]>

In [17]:
df_long.dtypes

Unnamed: 0      int64
country        object
year            int64
key            object
cases         float64
dtype: object

In [18]:
df_long["key"].value_counts()

new_sp_m4554    3223
new_sp_m3544    3219
new_sp_m5564    3218
new_sp_m1524    3209
new_sp_m65      3209
new_sp_m2534    3206
new_sp_f4554    3204
new_sp_f2534    3200
new_sp_f3544    3199
new_sp_f65      3197
new_sp_f5564    3195
new_sp_f1524    3194
new_sp_f014     3174
new_sp_m014     3173
new_sn_m014     1045
new_sn_f014     1040
new_ep_m014     1038
new_ep_f014     1032
new_sn_m1524    1030
new_sn_m4554    1027
new_ep_m1524    1026
new_sn_m3544    1025
new_ep_m3544    1024
new_sn_m2534    1022
new_sn_f1524    1022
new_ep_f3544    1021
new_sn_m5564    1021
new_ep_f1524    1021
new_ep_f2534    1021
new_sn_f3544    1020
new_sn_m65      1020
new_ep_m2534    1020
new_ep_m4554    1020
new_sn_f65      1019
new_sn_f4554    1018
new_ep_m65      1018
new_sn_f5564    1017
new_ep_f5564    1017
new_ep_f4554    1017
new_sn_f2534    1016
new_ep_m5564    1015
new_ep_f65      1014
newrel_f014      190
newrel_m014      190
newrel_f65       185
newrel_m5564     185
newrel_f1524     184
newrel_m3544     184
newrel_m4554     184
newrel_f3544     183
newrel_f4554     183
newrel_f5564     183
newrel_m2534     183
newrel_f2534     182
newrel_m1524     182
newrel_m65       182
Name: key, dtype: int64

In [19]:
df_long["country"].value_counts()

Canada               672
Switzerland          658
Israel               644
Cook Islands         576
Honduras             462
                    ...
South Sudan           42
Aruba                 37
San Marino            36
US Virgin Islands     21
Monaco                15
Name: country, Length: 219, dtype: int64

**Replace newrel with "new_rel" from key column**

In [20]:

df_long['key'] = df_long['key'].str.replace('newrel', 'new_rel')

In [21]:
split = df_long['key'].str.split("_", n=2, expand=True)

In [22]:
df_long["new"] = split[0]
df_long["type"] = split[1]
df_long["sexage"] = split[2]

In [23]:
df_long.head(5)

    Unnamed: 0  country  year          key  cases  new type sexage
60          61  Albania  2006  new_ep_f014    7.0  new   ep   f014
61          62  Albania  2007  new_ep_f014    1.0  new   ep   f014
62          63  Albania  2008  new_ep_f014    3.0  new   ep   f014
63          64  Albania  2009  new_ep_f014    2.0  new   ep   f014
64          65  Albania  2010  new_ep_f014    2.0  new   ep   f014

**Drop column "new" and split sexage column also**

In [24]:
df_long = df_long.drop(['new'], axis=1)

In [25]:
df_long[['sex', 'age']] = df_long['sexage'].str.extract('([a-zA-Z]+)([0-9]+)')

In [26]:
df_long.head(5)

    Unnamed: 0  country  year          key  cases type sexage sex  age
60          61  Albania  2006  new_ep_f014    7.0   ep   f014   f  014
61          62  Albania  2007  new_ep_f014    1.0   ep   f014   f  014
62          63  Albania  2008  new_ep_f014    3.0   ep   f014   f  014
63          64  Albania  2009  new_ep_f014    2.0   ep   f014   f  014
64          65  Albania  2010  new_ep_f014    2.0   ep   f014   f  014

In [27]:
df_long = df_long.drop(['sexage','Unnamed: 0'], axis=1)

In [28]:
df_long = df_long.drop(['key'], axis=1)

In [29]:
def MissingValues():
  country = df_long['country'].isna().sum()
  year = df_long['year'].isna().sum()
  cases = df_long['cases'].isna().sum()
  types = df_long['type'].isna().sum()
  sex = df_long['sex'].isna().sum()
  age = df_long['age'].isna().sum()
  print(country)
  print("Missing Values")
  print(country,year,cases,types,sex,age)
MissingValues()

0
Missing Values
0 0 0 0 0 0

In [30]:
df_long.dtypes

country     object
year         int64
cases      float64
type        object
sex         object
age         object
dtype: object

In [31]:
df_long.head(5)

    country  year  cases type sex  age
60  Albania  2006    7.0   ep   f  014
61  Albania  2007    1.0   ep   f  014
62  Albania  2008    3.0   ep   f  014
63  Albania  2009    2.0   ep   f  014
64  Albania  2010    2.0   ep   f  014

In [32]:
df_long['age'] = df_long['age'].astype('int')

In [33]:
df_long['age'].nunique()

7

In [34]:
def replace_values(value):
    if value == 14:
        return '0-14'
    elif value == 4554:
        return '45-54'
    elif value == 3544:
        return '35-44'
    elif value == 1524:
        return '15-24'
    elif value == 5564:
        return '55-64'
    elif value == 2534:
        return '25-34'
    else:
        return '65-above'

# Apply the custom function to the specified column
df_long['age'] = df_long['age'].apply(replace_values)

In [35]:
df_long['age'].value_counts()

0-14        10882
45-54       10876
35-44       10875
15-24       10868
55-64       10851
25-34       10850
65-above    10844
Name: age, dtype: int64

In [36]:
df_long.head(5)

    country  year  cases type sex   age
60  Albania  2006    7.0   ep   f  0-14
61  Albania  2007    1.0   ep   f  0-14
62  Albania  2008    3.0   ep   f  0-14
63  Albania  2009    2.0   ep   f  0-14
64  Albania  2010    2.0   ep   f  0-14

In [37]:
df_long.to_csv(r"cleaned_data_sample", index=False)

**Data Is Cleaned.**